from nltk.translate import meteor_score as ms 
# import nltk
# nltk.download('wordnet')
# hypo = {}
# ref = {}

# hypo[0] = 'this is the model generated sentence1 which seems good enough'
# ref[0] = ['this is one reference sentence for sentence1',
#         'this is a hey reference sentence for sentence2 which was generated by your model']

#score = ms.meteor_score(ref, hypo)
#print(score)

def compute_meteor(references, hypotheses):
    imgIds = references.keys()
    scores = [ms.meteor_score(references[id], hypotheses[id][0]) for id in imgIds]
    average_score = sum(scores) / len(scores)
    return average_score



